### ISSUE TITLE
Review Section 4 (High-Level Overview of the Realization Model)

### ISSUE THREAD

**Issue by boucadair** [boucadair/5g-slice-realization#10]
Start sharpening text, identify flaws/issues/missing items and report them, enhance readability, back text with relevant references, etc.

**Comment by julianL999** [comment]
Now complete, I made some minor edits

**Comment by boucadair** [comment]
Thanks @julianL999.

Wouldn't you think that adding some subsections/headings are needed before the current 4.* to better reflect the high level overview?  

CURRENT:

> [4](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#section-4).  [High-Level Overview of the Realization Model](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#name-high-level-overview-of-the-)
> 
> [4.1](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#section-4.1).  [VLAN Hand-off](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#name-vlan-hand-off)
> 
> [4.2](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#section-4.2).  [IP Hand-off](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#name-ip-hand-off)
> 
> [4.3](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#section-4.3).  [MPLS Label Hand-off](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#name-mpls-label-hand-off)
> 
> [4.3.1](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#section-4.3.1).  [Option 10A](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#name-option-10a)
> 
> [4.3.2](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#section-4.3.2).  [Option 10B](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#name-option-10b)
> 
> [4.3.3](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#section-4.3.3).  [Option 10C](https://boucadair.github.io/5g-slice-realization/draft-srld-teas-5g-slicing.html#name-option-10c)

**Comment by julianL999** [comment]
Hi Med
Not sure what headings you have in mind?
thanks
Julian

    On Friday, 17 March 2023 at 10:48:25 GMT, Med ***@***.***> wrote:  
 
 


Thanks @julianL999.

Wouldn't you think that adding some subsections/headings are needed before the current 4.* to better reflect the high level overview?

CURRENT:


4. High-Level Overview of the Realization Model

4.1. VLAN Hand-off

4.2. IP Hand-off

4.3. MPLS Label Hand-off

4.3.1. Option 10A

4.3.2. Option 10B

4.3.3. Option 10C

**Comment by boucadair** [comment]
> Hi Med Not sure what headings you have in mind?

What I had in mind is to have a ToC the echoes the key components of the realization approach in the draft, e.g.: 

> 4. High-Level Overview of the Realization Model
> 4.x VPN Technologies
> 4.x Resource & Admission Control
> 4.x Traffic Mapping or (SOME TITLE to group the VLAN/IP/MPLS subsections)
> etc.
