### ISSUE TITLE
list of update - https://datatracker.ietf.org/doc/draft-ietf-teas-5g-ns-ip-mpls/

### ISSUE THREAD

**Issue by robric** [boucadair/5g-slice-realization#113]
- Title of section 4 is not representative of the content 
- Need to modify text in 4.2 to have non IP headers identifiers that not IP address: DSCP-based slice identification, label, ports...
- Titles 3.4.2 and 3.5 (fsee answer to Daniele feedback)

**Comment by kszarkowicz** [comment]
4.2 still requires fixing (4 and 3.4.2 and 3.5 already fixed)
