### ISSUE TITLE
Implication of change of S-NSSAI on IP/VLAN Addressing

### ISSUE THREAD

**Issue by boucadair** [boucadair/5g-slice-realization#117]

**Comment by kszarkowicz** [comment]
Current text:

"One benefit of embedding the S-NSSAI in the IPv6 address is that specific S-NSSAI can be identified as interesting at any place in the TN domain. This might be used, for example, to selectively enable per S-NSSAI monitoring, traffic engineering or any other per S-NSSAI handling, if required.

However, operators using such mapping method should be aware of the implications of any change of S-NSSAI on the addressing plans. It is out of scope of this document to elaborate on these implications."

Alvaro's comments: 

"this document leaves several important pieces for the
realization out of scope.  I wonder if some of these are the "proposed
solutions" mentioned in RFC XXXX.  For example: implications of any change of S-NSSAI on the addressing plans"
