### ISSUE TITLE
(5.2.1.2. Outbound Edge Resource Control) Check the language

### ISSUE THREAD

**Issue by boucadair** [boucadair/5g-slice-realization#118]
> While inbound slice admission control at the provider network edge is mandatory in the architecture described in this document, outbound provider network edge resource control might not be required in all use cases. Use cases that specifically call for outbound provider network edge resource control are

From Alvaro: "Note that only one mention of a "mandatory (function) in the architecture described in this document" is present in the whole document (Section 5.2.1.2.  Outbound Edge Resource Control) -- making everything else optional and requiring some guidance."

**Comment by kszarkowicz** [comment]
Corrected in Section 5.

However, there are occurrences of 'must' in earlier sections.
