### ISSUE TITLE
Review Section 7 (Capacity Planning/Management)

### ISSUE THREAD

**Issue by boucadair** [boucadair/5g-slice-realization#13]
Start sharpening text, identify flaws/issues/missing items and report them, enhance readability, back text with relevant references, etc.

**Comment by julianL999** [comment]
I have done a review and posted changed version last week (sorry I should have commented here at the time)

**Comment by boucadair** [comment]
@luismcontreras, this is a nudge for this pending issue. Can you please look at this? Thanls.

**Comment by boucadair** [comment]
Closed as this is over due.
