### ISSUE TITLE
fixes to Section 7 from WG LC

### ISSUE THREAD

**Issue by julianL999** [boucadair/5g-slice-realization#173]
Address Adrian Farrel's comments on Section 7 in the WG LC:

---

7.2.1

I think the solution to handling variations in demand is what is
sometimes called "metric tweaking".

---

7.2.2 and 7.2.3

I'm not sure that SR-TE as described in 9256 is limited to LSPs. You
might just say "path".

---

7.2.3 seems to be floating a few ways of doing things in a rather
hypothetical way. Shouldn't you be referencing the technologies that
enable this?

---

**Comment by boucadair** [comment]
Thanks, Julian. 

For the second comment in the list, please use https://github.com/boucadair/5g-slice-realization/pull/151/files as startup. Thanks.

**Comment by julianL999** [comment]
now fixed
