### ISSUE TITLE
Section 5

### ISSUE THREAD

**Issue by boucadair** [boucadair/5g-slice-realization#178]
> ---
> 
> Section 5 is also clear, but seems really, really complex. I
> wonder whether these techniques are likely to be error-prone.
> 
> I'd be particularly interested to know what arrangements are
> needed when the TN is comprised of multiple administrative
> domains (possibly from different providers). How are the uses of
> QoS codepoints coordinated and maintained?

**Comment by kszarkowicz** [comment]
QoS framework is one of the important toolset for SLA guarantees, therefore described here in details.

QoS mapping and eventual mapping co-ordination between domains is out-of-scope for this document, and is left to I-D.cbs-teas-5qi-to-dscp-mapping document, which is referenced by our draft.
