### ISSUE TITLE
4.3.2 and 4.3.3  BGP Extensions

### ISSUE THREAD

**Issue by boucadair** [boucadair/5g-slice-realization#179]
> ---
> 
> 4.3.2 and 4.3.3
> 
> Just wondering whether these use an existing BGP mechanism (in
> which case, add a reference), or need a small protocol extension
> to define the community that matches a slice.

**Comment by kszarkowicz** [comment]
Using existing mechanisms is already described in the draft. This draft has no intention to define new mechanisms.

"It is worth noting that slice identification in the BGP control plane might be with per-prefix granularity. In the extreme case, each prefix can have different community representing a different slice. Depending on the business requirements, each slice could be represented by a different service instance, as outlined in [Figure 16](https://datatracker.ietf.org/doc/html/draft-ietf-teas-5g-ns-ip-mpls#_figure-mpls-10b-hand-off). In that case, the route target extended community might be used as slice differentiator. In other deployments, all prefixes (representing different slices) might be handled by a single 'mobile' service instance, and some other BGP attribute (e.g., a standard community) might be used for slice differentiation. There could be also a deployment option that groups multiple slices together into a single service instance, resulting in a handful of service instances. In any case, fine-grained per-hop behavior at the edge of provider network is possible."
