### ISSUE TITLE
First 5G Slice versus Subsequent Slices

### ISSUE THREAD

**Issue by boucadair** [boucadair/5g-slice-realization#19]
From @reza-github:

> 3.4.  First 5G Slice versus Subsequent Slices
> 
>    A 5G Network Slice is fully functional with both 5G Control Plane and
>    User Plane capabilities (i.e., dedicated NF functions or contexts).
>    In this regard, the creation of the "first slice" is subject to a
>    specific logic since it must deploy both CP and UP.  This is not the
>    case for the deployment of subsequent slices because they can share
>    the same CP of the first slice, while instantiating dedicated UP.  An
>    example of an incremental deployment is depicted in Figure 7 .

"Not clear. We need to talk about. Referring to Figure-7, creation of INS-3 still need to availability of the resource in the transport network. Unless you would like to convey another concept. Needs clarification."

**Comment by robric** [comment]
ok let's discuss this point during the call.

**Comment by boucadair** [comment]
I agree with @reza-github here that this section does not bring much to the realization model. I tend to suggest deleting this section.

**Comment by robric** [comment]
need discussion - to me this is simplified already... Need advices.

**Comment by boucadair** [comment]
> need discussion - to me this is simplified already... Need advices.

@robric, please check https://github.com/boucadair/5g-slice-realization/pull/56/files and adjust that text as appropriate. Thanks.
