### ISSUE TITLE
should we restrict to IETF API for TN orchestration ? 

### ISSUE THREAD

**Issue by robric** [boucadair/5g-slice-realization#2]
Section 3.2.2 may be too restrictive since it mandates the use of IETF API.  However, TMF APIs are also very common at this level of abstraction. We may rather focus on data models instead of API and not be restrictive on APIs (we can recommend IETF API though).

R
quoting:
"
In this document, and aligned with {{?RFC8969}}, we assume that this coordination is based upon
   IETF YANG data models and APIs (more details in further sections).
"

**Comment by boucadair** [comment]
The IETF mention was mainly to reflect the models that are currently called in the draft. The key point is to rely on standard DMs/APIs. Please see [09e8628](https://github.com/boucadair/5g-slice-realization/commit/09e8628132ca44edb74964b9659353f96606a5ed)
