### ISSUE TITLE
 Scope of Transport network vs RAN and CN,

### ISSUE THREAD

**Issue by kszarkowicz** [boucadair/5g-slice-realization#46]
Jie comments: Section 3.1 provides a picture about the scope of Transport network vs RAN and CN, while in the picture it is not clear where the NFs of RAN and CN reside in. Should they also be part of the DC or the public cloud? And TN only provides the connectivity in the DC and cloud.

Action: make the picture more clear.

**Comment by robric** [comment]
Update section 3.1:
- rename the Figure 1: Example of TN decomposition
- change the name of the 5G NF (RAN or CN)
