### ISSUE TITLE
reasoning why TN resources can be shared in the backhaul, while dedicated resource is needed in the midhaul

### ISSUE THREAD

**Issue by kszarkowicz** [boucadair/5g-slice-realization#47]
Jie comments: ection 3.2 gives an example of TN slice resource management: “For example, shared TN resources could be provided in the backhaul, and dedicated TN resources could be provided in the midhaul.” Suggest to provide some reasoning why TN resources can be shared in the backhaul, while dedicated resource is needed in the midhaul.

**Comment by robric** [comment]
I might just delete so people stop asking questions ?

**Comment by boucadair** [comment]
That text is only an example, not a recommendation. It should be contextualized as per: 

> TN Slicing provides **various degrees of sharing of resources** between slices. _For example_, the network capacity can be shared by all slices, usually with a guaranteed minimum per slice, or each individual slice can be allocated dedicated network capacity. Parts of a given network may use the former, while others use the latter. For example, shared TN resources could be provided in the backhaul, and dedicated TN resources could be provided in the midhaul.

Anyway, I suggest we simply go for the following change:

> TN Slicing provides **various degrees of sharing of resources** between slices. _For example_, the network capacity can be shared by all slices, usually with a guaranteed minimum per slice, or each individual slice can be allocated dedicated network capacity. Parts of a given network may use the former, while others use the latter. For example, **and in order to satisfy local engineering guidelines and specific service requirements**, shared TN resources could be provided in the backhaul, and dedicated TN resources could be provided in the midhaul. **The capacity partitioning strategy is deployment specific**.
