### ISSUE TITLE
The first and the subsequent 5G network slices

### ISSUE THREAD

**Issue by kszarkowicz** [boucadair/5g-slice-realization#48]
Jie comments: Section 3.6. This section describes the first and the subsequent 5G network slices, For this document it may also need to describe the implications to the realization of IETF network slices. The figure shows some mapping examples, while some text would be helpful.

Action: put more clarity in the text

**Comment by boucadair** [comment]
This one is redundant with https://github.com/boucadair/5g-slice-realization/issues/19
