### ISSUE TITLE
Reworking IP hand-off (VZ comments)

### ISSUE THREAD

**Issue by kszarkowicz** [boucadair/5g-slice-realization#81]
VZ proposed text:

In this option, the slice's specific S-NSSAI is mapped to a specific IP at each NF.  The IP is then defined as "interesting" and available for manipulation via multiple policy options in the IP network.   There are multiple mapping schemes that can be utilized where NSSAI equals IP (e.g. S-NSSAI to IPv4, S-NSSAI to IPv6).  These schemes can be single attach point specific or TN wide, for instance 1 S-NSSAI to 1 IP at each NF, 1 S-NSSAI to a pool of IP's for TN wide or 1 S-NSSAI to a subsection of IP address.  The IP and VLAN hand-off's are not mutually exclusive, but instead could be used together.  Since the TN doesn't recognize S-NSSAI, a mapping table similar to the VLAN Hand-off solution must be utilized.
 
The mapping table can be simplified if, for example, IPv6 addressing is used to address NFs. An IPv6 address is a 128-bit long field, while the S-NSSAI is a 32-bit field: Slice/Service Type (SST): 8 bits, Slice Differentiator (SD): 24 bits. 32 bits, out of 128 bits of the IPv6 address, may be used to encode the S-NSSAI, which makes an IP to Slice mapping table unnecessary. Alternatively, instead of using 2 full segments from the 8 segments in an IPv6 address, a provider could build a mapping table that used only one segment or parts of a segment to represent utilized S-NSSAI. This mapping is simply a local allocation method to allocate IPv6 addresses to NF in order to be representative of the S-NSSAI without redefining IPv6 semantics. Different IPv6 address allocation schemes following this approach may be used, with one example allocation shown in Figure 14.  
 
Note that this addressing scheme is local to an ingress or egress NF; intermediary TN nodes are not required to associate any additional semantic with IPv6 address.

One benefit of embedding the S-NSSAI in the IPv6 address is that specific S-NSSAI can be identified as interesting at any place in the TN domain. This might be used, for example, to selectively enable per S-NSSAI monitoring, traffic engineer or any other per S-NSSAI handling, if required.

In the example shown in Figure 14, the most significant 96 bits of the IPv6 address are unique to the NF, but do not carry any slice-specific information, while the least significant 32 bits are used to embed the S-NSSAI information. The 96-bit part of the address may then be engineered/architected by the provider, for example, on the geographical location or the DC identification.

Figure 15 uses the example from Figure 14 to demonstrate a slicing deployment where the entire S-NSSAI is embedded into IPv6 addresses used by NFs. NF-A has a set of tunnel termination points, with unique per-slice IP addresses allocated from the 2001:db8:a:0::/96 prefix, while NF-B uses a set of tunnel termination points with per-slice IP addresses allocated from 2001:db8:b:0::/96. This example shows two slices: customer A eMBB (SST=01, SD=00001) and customer B MIoT (SST=03, SD=00003). Therefore, for customer A eMBB the tunnel IP addresses are auto-derived (without the need for a mapping table) as the IP's {2001:db8:a:100::, 2001:db8:b:100::} simply add {:0100:0001}  as the IP's {2001:db8:a::100:0001, 2001:db8:b::100:0001} simply add {:0100:0001} as the last 2 segments and for customer B MIoT (SST=3) tunnel uses the IP's {2001:db8:a::300:0003, 2001:db8:b::300:0003} and simply adds {:0300:0003} as the last 2 segments.

Also, Figure 15 would need to be updated to reflect the changes,

**Comment by boucadair** [comment]
fixed #95
