### ISSUE TITLE
Review Section 3 (5G Network Slicing Integration in Transport Networks)

### ISSUE THREAD

**Issue by boucadair** [boucadair/5g-slice-realization#9]
Start sharpening text, identify flaws/issues/missing items and report them, enhance readability, back text with relevant references, etc.

**Comment by boucadair** [comment]
The new text uses "sections" to refer to "administrative scope" which unfortunate. 

> ### TN Sections and Network Slice Instantiation

**Comment by robric** [comment]
Well not exactly we have 3 sectiosn and 2 admin scopes - they are related but they don't map to the same thing.
This is a way to ignore the CS section and concentrate on AC And Provider network.

Regards
R




Juniper Business Use Only
